# Generated by Django 5.0.6 on 2024-06-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sensordata_servomotorstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
